<ErrorScreen>:
    Screen:
        Image:
            source: "libs/components/images/login.jpg"
            size_hint : None, None
            width : "360dp"
            height : "640dp"
            pos_hint : {'center_x':.5 , 'center_y':.5}
        Label:
            text: "Server is down, please try again later."
            size: self.texture_size
            font_size: '16sp'
            color: 1, 1, 1, 1 
            pos_hint: {'center_x': .5 , 'center_y': .5}